version: '3'

services:

  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    restart: unless-stopped
    ports:
      - "8200:8000"
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

volumes:
  yacht: