version: '3'
services:
  mlflow:
    container_name: mlflow
    build:
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./mlflow:/mlflow
    networks:
      - project_network

networks:
  project_network:
    external: true 